apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-<stage>
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: <stage>
    server: 'https://kubernetes.default.svc'
  source:
    path: 'deployment'
    repoURL: 'https://github.com/FlyingDogFood/gitops-example.git'
    targetRevision: <stage>
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
